"""
This type stub file was generated by pyright.
"""

from .backend import Backend, cast, instantiate_backend, select_backend

"""
The :mod:`tslearn.backend` module provides multiple backends.
The backends provided are NumPy and PyTorch.
"""
__all__ = ["Backend", "cast", "instantiate_backend", "select_backend"]
