"""
This type stub file was generated by pyright.
"""

"""The Numpy backend.

Several backend functions are inspired from a python package about Machine Learning
in Riemannian manifolds named geomstats [JMLR:v21:19-027], also implementing several backends.

References
----------------
[JMLR:v21:19-027] Nina Miolane, Nicolas Guigui, Alice Le Brigant, Johan Mathe,
Benjamin Hou, Yann Thanwerdas, Stefan Heyder, Olivier Peltre, Niklas Koep, Hadi Zaatiti,
Hatem Hajri, Yann Cabanes, Thomas Gerald, Paul Chauchat, Christian Shewmake, Daniel Brooks,
Bernhard Kainz, Claire Donnat, Susan Holmes and Xavier Pennec.
Geomstats:  A Python Package for Riemannian Geometry in Machine Learning,
Journal of Machine Learning Research, 2020, volume 21, number 223, pages 1-9,
http://jmlr.org/papers/v21/19-027.html, https://github.com/geomstats/geomstats/
"""
class NumPyBackend:
    """Class for the Numpy  backend."""
    def __init__(self) -> None:
        ...
    
    @staticmethod
    def belongs_to_backend(x): # -> bool:
        ...
    
    @staticmethod
    def cast(x, dtype):
        ...
    
    @staticmethod
    def copy(x):
        ...
    
    @staticmethod
    def from_numpy(x):
        ...
    
    @staticmethod
    def is_array(x): # -> bool:
        ...
    
    @staticmethod
    def is_float(x): # -> bool:
        ...
    
    @staticmethod
    def is_float32(x): # -> bool:
        ...
    
    @staticmethod
    def is_float64(x): # -> bool:
        ...
    
    @staticmethod
    def ndim(x):
        ...
    
    @staticmethod
    def to_numpy(x):
        ...
    


class NumPyLinalg:
    def __init__(self) -> None:
        ...
    


class NumPyRandom:
    def __init__(self) -> None:
        ...
    


class NumPyTesting:
    def __init__(self) -> None:
        ...
    


