"""
This type stub file was generated by pyright.
"""

from .kshape import KShape
from .utils import EmptyClusterError, TimeSeriesCentroidBasedClusteringMixin, silhouette_score
from .kmeans import KernelKMeans, TimeSeriesKMeans

"""
The :mod:`tslearn.clustering` module gathers time series specific clustering
algorithms.

**User guide:** See the :ref:`Clustering <clustering>` section for further 
 details.
"""
__author__ = ...
__all__ = ["KShape", "EmptyClusterError", "silhouette_score", "TimeSeriesCentroidBasedClusteringMixin", "TimeSeriesKMeans", "KernelKMeans"]
