"""
This type stub file was generated by pyright.
"""

from abc import ABCMeta
from sklearn.base import BaseEstimator

h5py_msg = ...
_DEFAULT_TAGS = ...
class TimeSeriesBaseEstimator(BaseEstimator):
    ...


class BaseModelPackage:
    __metaclass__ = ABCMeta
    def to_hdf5(self, path): # -> None:
        """
        Save model to a HDF5 file.
        Requires ``h5py`` http://docs.h5py.org/

        Parameters
        ----------
        path : str
            Full file path. File must not already exist.

        Raises
        ------
        FileExistsError
            If a file with the same path already exists.
        """
        ...
    
    @classmethod
    def from_hdf5(cls, path):
        """
        Load model from a HDF5 file.
        Requires ``h5py`` http://docs.h5py.org/

        Parameters
        ----------
        path : str
            Full path to file.

        Returns
        -------
        Model instance
        """
        ...
    
    def to_json(self, path): # -> None:
        """
        Save model to a JSON file.

        Parameters
        ----------
        path : str
            Full file path.
        """
        ...
    
    @classmethod
    def from_json(cls, path):
        """
        Load model from a JSON file.

        Parameters
        ----------
        path : str
            Full path to file.

        Returns
        -------
        Model instance
        """
        ...
    
    def to_pickle(self, path): # -> None:
        """
        Save model to a pickle file.

        Parameters
        ----------
        path : str
            Full file path.
        """
        ...
    
    @classmethod
    def from_pickle(cls, path):
        """
        Load model from a pickle file.

        Parameters
        ----------
        path : str
            Full path to file.

        Returns
        -------
        Model instance
        """
        ...
    


