"""
This type stub file was generated by pyright.
"""

from .dtw_variants import GLOBAL_CONSTRAINT_CODE, cdist_dtw, dtw, dtw_limited_warping_length, dtw_path, dtw_path_from_metric, dtw_path_limited_warping_length, dtw_subsequence_path, itakura_mask, lb_envelope, lb_keogh, lcss, lcss_path, lcss_path_from_metric, sakoe_chiba_mask, subsequence_cost_matrix, subsequence_path
from .ctw import cdist_ctw, ctw, ctw_path
from .sax import cdist_sax
from .softdtw_variants import SoftDTW, SquaredEuclidean, cdist_gak, cdist_soft_dtw, cdist_soft_dtw_normalized, gak, gamma_soft_dtw, sigma_gak, soft_dtw, soft_dtw_alignment
from .soft_dtw_loss_pytorch import SoftDTWLossPyTorch
from .cycc import cdist_normalized_cc, y_shifted_sbd_vec

"""
The :mod:`tslearn.metrics` module delivers time-series specific metrics to be 
used at the core of machine learning algorithms.

**User guide:** See the :ref:`Dynamic Time Warping (DTW) <dtw>` section for 
further details.
"""
__author__ = ...
TSLEARN_VALID_METRICS = ...
VARIABLE_LENGTH_METRICS = ...
__all__ = ["TSLEARN_VALID_METRICS", "VARIABLE_LENGTH_METRICS", "dtw", "dtw_limited_warping_length", "dtw_path_limited_warping_length", "subsequence_path", "subsequence_cost_matrix", "dtw_path", "dtw_path_from_metric", "dtw_subsequence_path", "cdist_dtw", "GLOBAL_CONSTRAINT_CODE", "lb_envelope", "lb_keogh", "sakoe_chiba_mask", "itakura_mask", "lcss", "lcss_path", "lcss_path_from_metric", "ctw_path", "ctw", "cdist_ctw", "cdist_sax", "cdist_soft_dtw", "cdist_gak", "cdist_soft_dtw_normalized", "gak", "soft_dtw", "soft_dtw_alignment", "sigma_gak", "gamma_soft_dtw", "SquaredEuclidean", "SoftDTW", "SoftDTWLossPyTorch", "cdist_normalized_cc", "y_shifted_sbd_vec"]
