"""
This type stub file was generated by pyright.
"""

from numba import njit

STUFF_cycc = ...
__author__ = ...
@njit(fastmath=True)
def normalized_cc(s1, s2, norm1=..., norm2=...): # -> Any:
    """Normalize cc.

    Parameters
    ----------
    s1 : array-like, shape=(sz, d), dtype=float64
        A time series.
    s2 : array-like, shape=(sz, d), dtype=float64
        Another time series.
    norm1 : float64, default=-1.0
    norm2 : float64, default=-1.0

    Returns
    -------
    norm_cc : array-like, shape=(2 * sz - 1), dtype=float64
    """
    ...

@njit(parallel=True, fastmath=True)
def cdist_normalized_cc(dataset1, dataset2, norms1, norms2, self_similarity): # -> ndarray[tuple[int, int], dtype[float64]]:
    """Compute the distance matrix between two time series dataset.

    Parameters
    ----------
    dataset1 : array-like, shape=(n_ts1, sz, d), dtype=float64
        A dataset of time series.
    dataset2 : array-like, shape=(n_ts2, sz, d), dtype=float64
        Another dataset of time series.
    norms1 : array-like, shape=(n_ts1,), dtype=float64
    norms2 : array-like, shape=(n_ts2,), dtype=float64
    self_similarity : bool

    Returns
    -------
    dists : array-like, shape=(n_ts1, n_ts2), dtype=float64
    """
    ...

@njit(parallel=True, fastmath=True)
def y_shifted_sbd_vec(ref_ts, dataset, norm_ref, norms_dataset): # -> _Array[tuple[int, int, int], float64]:
    """Shift a time series dataset w.r.t. a time series of reference.

    Parameters
    ----------
    ref_ts : array-like, shape=(sz, d), dtype=float64
        Time series of reference.
    dataset : array-like, shape=(n_ts, sz, d), dtype=float64
        Time series dataset.
    norm_ref : float64
    norms_dataset : array-like, shape=(n_ts,), dtype=float64
        Norms of the time series dataset.

    Returns
    -------
    dataset_shifted : array-like, shape=(n_ts, sz, d), dtype=float64
        Shifted dataset.
    """
    ...

