"""
This type stub file was generated by pyright.
"""

from .utils import LabelCategorizer, _load_arff_uea, _load_txt_uea, check_dataset, check_dims, check_equal_size, load_time_series_txt, load_timeseries_txt, save_time_series_txt, save_timeseries_txt, str_to_time_series, str_to_timeseries, time_series_to_str, timeseries_to_str, to_time_series, to_time_series_dataset, ts_size, ts_zeros
from .cast import from_cesium_dataset, from_pyflux_dataset, from_pyts_dataset, from_seglearn_dataset, from_sktime_dataset, from_stumpy_dataset, from_tsfresh_dataset, to_cesium_dataset, to_pyflux_dataset, to_pyts_dataset, to_seglearn_dataset, to_sklearn_dataset, to_sktime_dataset, to_stumpy_dataset, to_tsfresh_dataset

"""
The :mod:`tslearn.utils` module includes various utilities.
"""
__all__ = ["check_dims", "check_equal_size", "to_time_series", "to_time_series_dataset", "time_series_to_str", "timeseries_to_str", "str_to_time_series", "str_to_timeseries", "save_time_series_txt", "save_timeseries_txt", "load_time_series_txt", "load_timeseries_txt", "ts_size", "ts_zeros", "check_dataset", "LabelCategorizer", "_load_txt_uea", "_load_arff_uea" "to_sklearn_dataset", "from_cesium_dataset", "to_cesium_dataset", "from_pyflux_dataset", "to_pyflux_dataset", "from_pyts_dataset", "to_pyts_dataset", "from_seglearn_dataset", "to_seglearn_dataset", "from_sktime_dataset", "to_sktime_dataset", "from_stumpy_dataset", "to_stumpy_dataset", "from_tsfresh_dataset", "to_tsfresh_dataset"]
